/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotUsernameRouteImport } from './routes/forgot-username'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ConfirmSignupRouteImport } from './routes/confirm-signup'
import { Route as privateIndexRouteImport } from './routes/(private)/index'
import { Route as privateSettingsRouteImport } from './routes/(private)/settings'
import { Route as privateLayoutRouteImport } from './routes/(private)/_layout'
import { Route as authMfaIndexRouteImport } from './routes/(auth)/mfa/index'
import { Route as authMfaVerifyCodeRouteImport } from './routes/(auth)/mfa/verify-code'
import { Route as authMfaSmsRouteImport } from './routes/(auth)/mfa/sms'
import { Route as authMfaEmailRouteImport } from './routes/(auth)/mfa/email'
import { Route as authMfaConnectRouteImport } from './routes/(auth)/mfa/connect'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotUsernameRoute = ForgotUsernameRouteImport.update({
  id: '/forgot-username',
  path: '/forgot-username',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmSignupRoute = ConfirmSignupRouteImport.update({
  id: '/confirm-signup',
  path: '/confirm-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const privateIndexRoute = privateIndexRouteImport.update({
  id: '/(private)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const privateSettingsRoute = privateSettingsRouteImport.update({
  id: '/(private)/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const privateLayoutRoute = privateLayoutRouteImport.update({
  id: '/(private)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authMfaIndexRoute = authMfaIndexRouteImport.update({
  id: '/(auth)/mfa/',
  path: '/mfa/',
  getParentRoute: () => rootRouteImport,
} as any)
const authMfaVerifyCodeRoute = authMfaVerifyCodeRouteImport.update({
  id: '/(auth)/mfa/verify-code',
  path: '/mfa/verify-code',
  getParentRoute: () => rootRouteImport,
} as any)
const authMfaSmsRoute = authMfaSmsRouteImport.update({
  id: '/(auth)/mfa/sms',
  path: '/mfa/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const authMfaEmailRoute = authMfaEmailRouteImport.update({
  id: '/(auth)/mfa/email',
  path: '/mfa/email',
  getParentRoute: () => rootRouteImport,
} as any)
const authMfaConnectRoute = authMfaConnectRouteImport.update({
  id: '/(auth)/mfa/connect',
  path: '/mfa/connect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/confirm-signup': typeof ConfirmSignupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/forgot-username': typeof ForgotUsernameRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/settings': typeof privateSettingsRoute
  '/': typeof privateIndexRoute
  '/mfa/connect': typeof authMfaConnectRoute
  '/mfa/email': typeof authMfaEmailRoute
  '/mfa/sms': typeof authMfaSmsRoute
  '/mfa/verify-code': typeof authMfaVerifyCodeRoute
  '/mfa': typeof authMfaIndexRoute
}
export interface FileRoutesByTo {
  '/confirm-signup': typeof ConfirmSignupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/forgot-username': typeof ForgotUsernameRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/settings': typeof privateSettingsRoute
  '/': typeof privateIndexRoute
  '/mfa/connect': typeof authMfaConnectRoute
  '/mfa/email': typeof authMfaEmailRoute
  '/mfa/sms': typeof authMfaSmsRoute
  '/mfa/verify-code': typeof authMfaVerifyCodeRoute
  '/mfa': typeof authMfaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/confirm-signup': typeof ConfirmSignupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/forgot-username': typeof ForgotUsernameRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/(private)/_layout': typeof privateLayoutRoute
  '/(private)/settings': typeof privateSettingsRoute
  '/(private)/': typeof privateIndexRoute
  '/(auth)/mfa/connect': typeof authMfaConnectRoute
  '/(auth)/mfa/email': typeof authMfaEmailRoute
  '/(auth)/mfa/sms': typeof authMfaSmsRoute
  '/(auth)/mfa/verify-code': typeof authMfaVerifyCodeRoute
  '/(auth)/mfa/': typeof authMfaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/confirm-signup'
    | '/forgot-password'
    | '/forgot-username'
    | '/login'
    | '/logout'
    | '/privacy-policy'
    | '/reset-password'
    | '/signup'
    | '/terms-of-service'
    | '/settings'
    | '/'
    | '/mfa/connect'
    | '/mfa/email'
    | '/mfa/sms'
    | '/mfa/verify-code'
    | '/mfa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/confirm-signup'
    | '/forgot-password'
    | '/forgot-username'
    | '/login'
    | '/logout'
    | '/privacy-policy'
    | '/reset-password'
    | '/signup'
    | '/terms-of-service'
    | '/settings'
    | '/'
    | '/mfa/connect'
    | '/mfa/email'
    | '/mfa/sms'
    | '/mfa/verify-code'
    | '/mfa'
  id:
    | '__root__'
    | '/confirm-signup'
    | '/forgot-password'
    | '/forgot-username'
    | '/login'
    | '/logout'
    | '/privacy-policy'
    | '/reset-password'
    | '/signup'
    | '/terms-of-service'
    | '/(private)/_layout'
    | '/(private)/settings'
    | '/(private)/'
    | '/(auth)/mfa/connect'
    | '/(auth)/mfa/email'
    | '/(auth)/mfa/sms'
    | '/(auth)/mfa/verify-code'
    | '/(auth)/mfa/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConfirmSignupRoute: typeof ConfirmSignupRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ForgotUsernameRoute: typeof ForgotUsernameRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  privateLayoutRoute: typeof privateLayoutRoute
  privateSettingsRoute: typeof privateSettingsRoute
  privateIndexRoute: typeof privateIndexRoute
  authMfaConnectRoute: typeof authMfaConnectRoute
  authMfaEmailRoute: typeof authMfaEmailRoute
  authMfaSmsRoute: typeof authMfaSmsRoute
  authMfaVerifyCodeRoute: typeof authMfaVerifyCodeRoute
  authMfaIndexRoute: typeof authMfaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-username': {
      id: '/forgot-username'
      path: '/forgot-username'
      fullPath: '/forgot-username'
      preLoaderRoute: typeof ForgotUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-signup': {
      id: '/confirm-signup'
      path: '/confirm-signup'
      fullPath: '/confirm-signup'
      preLoaderRoute: typeof ConfirmSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/': {
      id: '/(private)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof privateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/settings': {
      id: '/(private)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof privateSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/_layout': {
      id: '/(private)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/mfa/': {
      id: '/(auth)/mfa/'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof authMfaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/mfa/verify-code': {
      id: '/(auth)/mfa/verify-code'
      path: '/mfa/verify-code'
      fullPath: '/mfa/verify-code'
      preLoaderRoute: typeof authMfaVerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/mfa/sms': {
      id: '/(auth)/mfa/sms'
      path: '/mfa/sms'
      fullPath: '/mfa/sms'
      preLoaderRoute: typeof authMfaSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/mfa/email': {
      id: '/(auth)/mfa/email'
      path: '/mfa/email'
      fullPath: '/mfa/email'
      preLoaderRoute: typeof authMfaEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/mfa/connect': {
      id: '/(auth)/mfa/connect'
      path: '/mfa/connect'
      fullPath: '/mfa/connect'
      preLoaderRoute: typeof authMfaConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ConfirmSignupRoute: ConfirmSignupRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ForgotUsernameRoute: ForgotUsernameRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  privateLayoutRoute: privateLayoutRoute,
  privateSettingsRoute: privateSettingsRoute,
  privateIndexRoute: privateIndexRoute,
  authMfaConnectRoute: authMfaConnectRoute,
  authMfaEmailRoute: authMfaEmailRoute,
  authMfaSmsRoute: authMfaSmsRoute,
  authMfaVerifyCodeRoute: authMfaVerifyCodeRoute,
  authMfaIndexRoute: authMfaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
