/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as MaintainanceRouteImport } from './routes/maintainance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as privatePrivateRouteImport } from './routes/(private)/_private'
import { Route as authAuthRouteImport } from './routes/(auth)/_auth'
import { Route as authMfaIndexRouteImport } from './routes/(auth)/mfa/index'
import { Route as privatePrivateSecuritySettingsRouteImport } from './routes/(private)/_private.security-settings'
import { Route as privatePrivateAccountSettingsRouteImport } from './routes/(private)/_private.account-settings'
import { Route as authOtpWebAuthRouteImport } from './routes/(auth)/otp/web-auth'
import { Route as authOtpSmsRouteImport } from './routes/(auth)/otp/sms'
import { Route as authOtpEmailRouteImport } from './routes/(auth)/otp/email'
import { Route as authMfaVerifyCodeRouteImport } from './routes/(auth)/mfa/verify-code'
import { Route as authMfaSmsRouteImport } from './routes/(auth)/mfa/sms'
import { Route as authMfaEmailRouteImport } from './routes/(auth)/mfa/email'
import { Route as authMfaConnectRouteImport } from './routes/(auth)/mfa/connect'
import { Route as authAuthVerifyUsernameRouteImport } from './routes/(auth)/_auth.verify-username'
import { Route as authAuthSignupRouteImport } from './routes/(auth)/_auth.signup'
import { Route as authAuthResetPasswordRouteImport } from './routes/(auth)/_auth.reset-password'
import { Route as authAuthLoginRouteImport } from './routes/(auth)/_auth.login'
import { Route as authAuthForgotUsernameRouteImport } from './routes/(auth)/_auth.forgot-username'
import { Route as authAuthForgotPasswordRouteImport } from './routes/(auth)/_auth.forgot-password'
import { Route as authAuthConfirmSignupRouteImport } from './routes/(auth)/_auth.confirm-signup'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintainanceRoute = MaintainanceRouteImport.update({
  id: '/maintainance',
  path: '/maintainance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const privatePrivateRoute = privatePrivateRouteImport.update({
  id: '/(private)/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const authMfaIndexRoute = authMfaIndexRouteImport.update({
  id: '/(auth)/mfa/',
  path: '/mfa/',
  getParentRoute: () => rootRouteImport,
} as any)
const privatePrivateSecuritySettingsRoute =
  privatePrivateSecuritySettingsRouteImport.update({
    id: '/security-settings',
    path: '/security-settings',
    getParentRoute: () => privatePrivateRoute,
  } as any)
const privatePrivateAccountSettingsRoute =
  privatePrivateAccountSettingsRouteImport.update({
    id: '/account-settings',
    path: '/account-settings',
    getParentRoute: () => privatePrivateRoute,
  } as any)
const authOtpWebAuthRoute = authOtpWebAuthRouteImport.update({
  id: '/(auth)/otp/web-auth',
  path: '/otp/web-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpSmsRoute = authOtpSmsRouteImport.update({
  id: '/(auth)/otp/sms',
  path: '/otp/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpEmailRoute = authOtpEmailRouteImport.update({
  id: '/(auth)/otp/email',
  path: '/otp/email',
  getParentRoute: () => rootRouteImport,
} as any)
const authMfaVerifyCodeRoute = authMfaVerifyCodeRouteImport.update({
  id: '/(auth)/mfa/verify-code',
  path: '/mfa/verify-code',
  getParentRoute: () => rootRouteImport,
} as any)
const authMfaSmsRoute = authMfaSmsRouteImport.update({
  id: '/(auth)/mfa/sms',
  path: '/mfa/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const authMfaEmailRoute = authMfaEmailRouteImport.update({
  id: '/(auth)/mfa/email',
  path: '/mfa/email',
  getParentRoute: () => rootRouteImport,
} as any)
const authMfaConnectRoute = authMfaConnectRouteImport.update({
  id: '/(auth)/mfa/connect',
  path: '/mfa/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthVerifyUsernameRoute = authAuthVerifyUsernameRouteImport.update({
  id: '/verify-username',
  path: '/verify-username',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthSignupRoute = authAuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthResetPasswordRoute = authAuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthForgotUsernameRoute = authAuthForgotUsernameRouteImport.update({
  id: '/forgot-username',
  path: '/forgot-username',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthForgotPasswordRoute = authAuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthConfirmSignupRoute = authAuthConfirmSignupRouteImport.update({
  id: '/confirm-signup',
  path: '/confirm-signup',
  getParentRoute: () => authAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/maintainance': typeof MaintainanceRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/confirm-signup': typeof authAuthConfirmSignupRoute
  '/forgot-password': typeof authAuthForgotPasswordRoute
  '/forgot-username': typeof authAuthForgotUsernameRoute
  '/login': typeof authAuthLoginRoute
  '/reset-password': typeof authAuthResetPasswordRoute
  '/signup': typeof authAuthSignupRoute
  '/verify-username': typeof authAuthVerifyUsernameRoute
  '/mfa/connect': typeof authMfaConnectRoute
  '/mfa/email': typeof authMfaEmailRoute
  '/mfa/sms': typeof authMfaSmsRoute
  '/mfa/verify-code': typeof authMfaVerifyCodeRoute
  '/otp/email': typeof authOtpEmailRoute
  '/otp/sms': typeof authOtpSmsRoute
  '/otp/web-auth': typeof authOtpWebAuthRoute
  '/account-settings': typeof privatePrivateAccountSettingsRoute
  '/security-settings': typeof privatePrivateSecuritySettingsRoute
  '/mfa': typeof authMfaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/maintainance': typeof MaintainanceRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/confirm-signup': typeof authAuthConfirmSignupRoute
  '/forgot-password': typeof authAuthForgotPasswordRoute
  '/forgot-username': typeof authAuthForgotUsernameRoute
  '/login': typeof authAuthLoginRoute
  '/reset-password': typeof authAuthResetPasswordRoute
  '/signup': typeof authAuthSignupRoute
  '/verify-username': typeof authAuthVerifyUsernameRoute
  '/mfa/connect': typeof authMfaConnectRoute
  '/mfa/email': typeof authMfaEmailRoute
  '/mfa/sms': typeof authMfaSmsRoute
  '/mfa/verify-code': typeof authMfaVerifyCodeRoute
  '/otp/email': typeof authOtpEmailRoute
  '/otp/sms': typeof authOtpSmsRoute
  '/otp/web-auth': typeof authOtpWebAuthRoute
  '/account-settings': typeof privatePrivateAccountSettingsRoute
  '/security-settings': typeof privatePrivateSecuritySettingsRoute
  '/mfa': typeof authMfaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/maintainance': typeof MaintainanceRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(private)/_private': typeof privatePrivateRouteWithChildren
  '/(auth)/_auth/confirm-signup': typeof authAuthConfirmSignupRoute
  '/(auth)/_auth/forgot-password': typeof authAuthForgotPasswordRoute
  '/(auth)/_auth/forgot-username': typeof authAuthForgotUsernameRoute
  '/(auth)/_auth/login': typeof authAuthLoginRoute
  '/(auth)/_auth/reset-password': typeof authAuthResetPasswordRoute
  '/(auth)/_auth/signup': typeof authAuthSignupRoute
  '/(auth)/_auth/verify-username': typeof authAuthVerifyUsernameRoute
  '/(auth)/mfa/connect': typeof authMfaConnectRoute
  '/(auth)/mfa/email': typeof authMfaEmailRoute
  '/(auth)/mfa/sms': typeof authMfaSmsRoute
  '/(auth)/mfa/verify-code': typeof authMfaVerifyCodeRoute
  '/(auth)/otp/email': typeof authOtpEmailRoute
  '/(auth)/otp/sms': typeof authOtpSmsRoute
  '/(auth)/otp/web-auth': typeof authOtpWebAuthRoute
  '/(private)/_private/account-settings': typeof privatePrivateAccountSettingsRoute
  '/(private)/_private/security-settings': typeof privatePrivateSecuritySettingsRoute
  '/(auth)/mfa/': typeof authMfaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/maintainance'
    | '/terms-of-service'
    | '/confirm-signup'
    | '/forgot-password'
    | '/forgot-username'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-username'
    | '/mfa/connect'
    | '/mfa/email'
    | '/mfa/sms'
    | '/mfa/verify-code'
    | '/otp/email'
    | '/otp/sms'
    | '/otp/web-auth'
    | '/account-settings'
    | '/security-settings'
    | '/mfa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/maintainance'
    | '/terms-of-service'
    | '/confirm-signup'
    | '/forgot-password'
    | '/forgot-username'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-username'
    | '/mfa/connect'
    | '/mfa/email'
    | '/mfa/sms'
    | '/mfa/verify-code'
    | '/otp/email'
    | '/otp/sms'
    | '/otp/web-auth'
    | '/account-settings'
    | '/security-settings'
    | '/mfa'
  id:
    | '__root__'
    | '/'
    | '/maintainance'
    | '/terms-of-service'
    | '/(auth)/_auth'
    | '/(private)/_private'
    | '/(auth)/_auth/confirm-signup'
    | '/(auth)/_auth/forgot-password'
    | '/(auth)/_auth/forgot-username'
    | '/(auth)/_auth/login'
    | '/(auth)/_auth/reset-password'
    | '/(auth)/_auth/signup'
    | '/(auth)/_auth/verify-username'
    | '/(auth)/mfa/connect'
    | '/(auth)/mfa/email'
    | '/(auth)/mfa/sms'
    | '/(auth)/mfa/verify-code'
    | '/(auth)/otp/email'
    | '/(auth)/otp/sms'
    | '/(auth)/otp/web-auth'
    | '/(private)/_private/account-settings'
    | '/(private)/_private/security-settings'
    | '/(auth)/mfa/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MaintainanceRoute: typeof MaintainanceRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  authAuthRoute: typeof authAuthRouteWithChildren
  privatePrivateRoute: typeof privatePrivateRouteWithChildren
  authMfaConnectRoute: typeof authMfaConnectRoute
  authMfaEmailRoute: typeof authMfaEmailRoute
  authMfaSmsRoute: typeof authMfaSmsRoute
  authMfaVerifyCodeRoute: typeof authMfaVerifyCodeRoute
  authOtpEmailRoute: typeof authOtpEmailRoute
  authOtpSmsRoute: typeof authOtpSmsRoute
  authOtpWebAuthRoute: typeof authOtpWebAuthRoute
  authMfaIndexRoute: typeof authMfaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintainance': {
      id: '/maintainance'
      path: '/maintainance'
      fullPath: '/maintainance'
      preLoaderRoute: typeof MaintainanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/_private': {
      id: '/(private)/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privatePrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/mfa/': {
      id: '/(auth)/mfa/'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof authMfaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/_private/security-settings': {
      id: '/(private)/_private/security-settings'
      path: '/security-settings'
      fullPath: '/security-settings'
      preLoaderRoute: typeof privatePrivateSecuritySettingsRouteImport
      parentRoute: typeof privatePrivateRoute
    }
    '/(private)/_private/account-settings': {
      id: '/(private)/_private/account-settings'
      path: '/account-settings'
      fullPath: '/account-settings'
      preLoaderRoute: typeof privatePrivateAccountSettingsRouteImport
      parentRoute: typeof privatePrivateRoute
    }
    '/(auth)/otp/web-auth': {
      id: '/(auth)/otp/web-auth'
      path: '/otp/web-auth'
      fullPath: '/otp/web-auth'
      preLoaderRoute: typeof authOtpWebAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp/sms': {
      id: '/(auth)/otp/sms'
      path: '/otp/sms'
      fullPath: '/otp/sms'
      preLoaderRoute: typeof authOtpSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp/email': {
      id: '/(auth)/otp/email'
      path: '/otp/email'
      fullPath: '/otp/email'
      preLoaderRoute: typeof authOtpEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/mfa/verify-code': {
      id: '/(auth)/mfa/verify-code'
      path: '/mfa/verify-code'
      fullPath: '/mfa/verify-code'
      preLoaderRoute: typeof authMfaVerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/mfa/sms': {
      id: '/(auth)/mfa/sms'
      path: '/mfa/sms'
      fullPath: '/mfa/sms'
      preLoaderRoute: typeof authMfaSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/mfa/email': {
      id: '/(auth)/mfa/email'
      path: '/mfa/email'
      fullPath: '/mfa/email'
      preLoaderRoute: typeof authMfaEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/mfa/connect': {
      id: '/(auth)/mfa/connect'
      path: '/mfa/connect'
      fullPath: '/mfa/connect'
      preLoaderRoute: typeof authMfaConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth/verify-username': {
      id: '/(auth)/_auth/verify-username'
      path: '/verify-username'
      fullPath: '/verify-username'
      preLoaderRoute: typeof authAuthVerifyUsernameRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/signup': {
      id: '/(auth)/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authAuthSignupRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/reset-password': {
      id: '/(auth)/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authAuthResetPasswordRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/login': {
      id: '/(auth)/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/forgot-username': {
      id: '/(auth)/_auth/forgot-username'
      path: '/forgot-username'
      fullPath: '/forgot-username'
      preLoaderRoute: typeof authAuthForgotUsernameRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/forgot-password': {
      id: '/(auth)/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authAuthForgotPasswordRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/confirm-signup': {
      id: '/(auth)/_auth/confirm-signup'
      path: '/confirm-signup'
      fullPath: '/confirm-signup'
      preLoaderRoute: typeof authAuthConfirmSignupRouteImport
      parentRoute: typeof authAuthRoute
    }
  }
}

interface authAuthRouteChildren {
  authAuthConfirmSignupRoute: typeof authAuthConfirmSignupRoute
  authAuthForgotPasswordRoute: typeof authAuthForgotPasswordRoute
  authAuthForgotUsernameRoute: typeof authAuthForgotUsernameRoute
  authAuthLoginRoute: typeof authAuthLoginRoute
  authAuthResetPasswordRoute: typeof authAuthResetPasswordRoute
  authAuthSignupRoute: typeof authAuthSignupRoute
  authAuthVerifyUsernameRoute: typeof authAuthVerifyUsernameRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthConfirmSignupRoute: authAuthConfirmSignupRoute,
  authAuthForgotPasswordRoute: authAuthForgotPasswordRoute,
  authAuthForgotUsernameRoute: authAuthForgotUsernameRoute,
  authAuthLoginRoute: authAuthLoginRoute,
  authAuthResetPasswordRoute: authAuthResetPasswordRoute,
  authAuthSignupRoute: authAuthSignupRoute,
  authAuthVerifyUsernameRoute: authAuthVerifyUsernameRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

interface privatePrivateRouteChildren {
  privatePrivateAccountSettingsRoute: typeof privatePrivateAccountSettingsRoute
  privatePrivateSecuritySettingsRoute: typeof privatePrivateSecuritySettingsRoute
}

const privatePrivateRouteChildren: privatePrivateRouteChildren = {
  privatePrivateAccountSettingsRoute: privatePrivateAccountSettingsRoute,
  privatePrivateSecuritySettingsRoute: privatePrivateSecuritySettingsRoute,
}

const privatePrivateRouteWithChildren = privatePrivateRoute._addFileChildren(
  privatePrivateRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MaintainanceRoute: MaintainanceRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  authAuthRoute: authAuthRouteWithChildren,
  privatePrivateRoute: privatePrivateRouteWithChildren,
  authMfaConnectRoute: authMfaConnectRoute,
  authMfaEmailRoute: authMfaEmailRoute,
  authMfaSmsRoute: authMfaSmsRoute,
  authMfaVerifyCodeRoute: authMfaVerifyCodeRoute,
  authOtpEmailRoute: authOtpEmailRoute,
  authOtpSmsRoute: authOtpSmsRoute,
  authOtpWebAuthRoute: authOtpWebAuthRoute,
  authMfaIndexRoute: authMfaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
